### ISSUE TITLE
HACS install/update error: "An error ocoured while prosessing" (404)

### ISSUE THREAD

**Issue by CodeFinder2** [benleb/ad-ench#6]
Hi,

sorry for another issue but I just tried to update your AppDaemon app (to test #5 ) via HACS (latest v0.20.4, latest Home Assistant v0.105.3) and it reports the error:
```text
An error ocoured while prosessing
GitHub returned 404 for https://api.github.com/repos/benleb/ad-ench/contents/apps/ench
```
I cannot update it. I therefore uninstalled it to (re-)install it afterwards but this is not working as well (same error). I tested [another app](https://github.com/xaviml/z2m_ikea_controller) just to check if [HACS](https://hacs.xyz/) works correctly at all and I was able to install/uninstall that app without any issues so I assume it must be related to your app/repo.

Interestingly, I can open the above link in my browser successfully ([click](https://api.github.com/repos/benleb/ad-ench/contents/apps/ench)).

Any ideas? :see_no_evil:

**Comment by dkalinai** [comment]
Just adding to it that I also have the same issue and with exactly same 404 on that repo...

**Comment by ludeeus** [comment]
The issue is that version 0.4.5 has the wrong content, and this is not compliant with HACS.
<https://github.com/benleb/ad-ench/tree/v0.4.5>

**Comment by CodeFinder2** [comment]
In what sense is it not compliant with HACS? There have only been minor internal changes and it was working fine with HACS previously (v0.4.4)?  (Sorry, I am not an expert of HACS or this app.)

Can you provide a PR to fix this quickly (or explain to me what is required for this to make it compatible again)?

Thanks!

**Comment by ludeeus** [comment]
The content of https://github.com/benleb/ad-ench/tree/v0.4.5 is **only** the `adutils` directory.
It's missing everything else that you find in both previous versions and in the `master` branch.

**Comment by benleb** [comment]
wow shit sorry, will fix this today! thanks @CodeFinder2 & @ludeeus

**Comment by benleb** [comment]
sorry, fixed in https://github.com/benleb/ad-ench/releases/tag/v0.4.6

The directory `apps/ench/adutils` is a submodule which points to https://github.com/benleb/adutils which is also tagged with "v0.4.5" at the moment. The command issued to tag and push was 
`$ bumpversion --verbose --tag --commit patch && git push && git push --tags` and resulted in the broken v0.4.5 release files, just inluding the submodules files. These are the automatically generated files by github, I did not upload them.

To fix the release, I changed nothing and reissued the above command to tag a "v0.4.6" (**not** available in the adutils submodule) which led github to produce a correct zip & tar.gz now. 
On the same day I added the same submodule to https://github.com/benleb/ad-automoli (which was already on a tag not available in the submodule), but this problem occurred only here, therefore the behaviour has probably something to do with the same tags in submodule and parent!?

Maybe someone knows and can explain what happened here?! 😅

**Comment by CodeFinder2** [comment]
Thanks for the fix but unfortunately, there are more errors (cannot find adutils import, but even after fixing that: `UnboundLocalError: local variable 'attrs' referenced before assignment`). 

Maybe you should try/test the app with Hassio :see_no_evil:

**Comment by CodeFinder2** [comment]
> The content of https://github.com/benleb/ad-ench/tree/v0.4.5 is **only** the content of the `adutils` directory.
> It's missing everything else that you find in both previous versions and in the `master` branch.

Wouldn't it be much better to print a more appropriate error message in HACS (something like "repo structure malformed, see bla-blub. Unable to find `<list-of-missing-files>`) than just a 404?

Even worse/confusing, the *referenced* / linked file actually exists.

**Comment by benleb** [comment]
@CodeFinder2 could you please try the v0.4.7 BETA released just now? (You have to enable beta releases in HACS for ad-ench first maybe) https://github.com/benleb/ad-ench/releases/tag/v0.4.7

And yes sorry, but there are soooo much ways people setup home assistant, I can and want not have a test setup for every way... But I know your feel and basically you are right, maybe i should think about more robust tests

**Comment by CodeFinder2** [comment]
No worries! 🙂

Installed the beta but not working, AppDaemon log:
```text
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: AppDaemon
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.1.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (armv7 / odroid-xu)
 Home Assistant version: 0.103.5
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[19:57:00] INFO: Updating Hass.io API token in AppDaemon with the current one...
Looking in links: https://wheels.hass.io/alpine-3.10/armv7/
Collecting adutils
  Downloading https://files.pythonhosted.org/packages/10/79/ecdeab6338d9cb90b45cb7a8ba4ad8d463ff6534c319a092076559105059/adutils-0.4.5-py3-none-any.whl
Installing collected packages: adutils
Successfully installed adutils-0.4.5
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:57:08] INFO: Starting AppDaemon...
2020-01-03 19:57:09.718572 INFO AppDaemon Version 3.0.5 starting
2020-01-03 19:57:09.719063 INFO Configuration read from: /config/appdaemon/appdaemon.yaml
2020-01-03 19:57:09.721612 INFO AppDaemon: Starting Apps
2020-01-03 19:57:09.728519 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-01-03 19:57:09.966911 INFO AppDaemon: HASS: HASS Plugin Initializing
2020-01-03 19:57:09.968033 INFO AppDaemon: HASS: HASS Plugin initialization complete
2020-01-03 19:57:09.968842 INFO Starting Dashboards
2020-01-03 19:57:09.987295 INFO API is disabled
2020-01-03 19:57:09.998419 INFO AppDaemon: HASS: Connected to Home Assistant 0.103.5
2020-01-03 19:57:10.172685 INFO AppDaemon: Got initial state from namespace default
2020-01-03 19:57:12.178630 INFO AppDaemon: Reading config
2020-01-03 19:57:12.195197 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-03 19:57:12.195476 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-03 19:57:12.195727 INFO AppDaemon: App 'hello_world' added
2020-01-03 19:57:12.195960 INFO AppDaemon: App 'ench' added
2020-01-03 19:57:12.196303 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-01-03 19:57:12.196737 INFO AppDaemon: Adding /config/appdaemon/apps/ench to module import path
2020-01-03 19:57:12.197140 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils to module import path
2020-01-03 19:57:12.197493 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/.github to module import path
2020-01-03 19:57:12.197826 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/.github/workflows to module import path
2020-01-03 19:57:12.198163 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/adutils to module import path
2020-01-03 19:57:12.199489 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2020-01-03 19:57:12.222989 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/ench/ench.py
2020-01-03 19:57:12.225214 WARNING AppDaemon: ------------------------------------------------------------
2020-01-03 19:57:12.225508 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/ench/ench.py:
2020-01-03 19:57:12.225731 WARNING AppDaemon: ------------------------------------------------------------
2020-01-03 19:57:12.230716 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/ench/ench.py", line 22, in <module>
    from .adutils import adutils
ImportError: attempted relative import with no known parent package

2020-01-03 19:57:12.231248 WARNING AppDaemon: ------------------------------------------------------------
2020-01-03 19:57:12.231542 WARNING AppDaemon: Removing associated apps:
2020-01-03 19:57:12.231880 WARNING AppDaemon: ench
2020-01-03 19:57:12.232330 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/ench/adutils/setup.py - ignoring
2020-01-03 19:57:12.232757 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/ench/adutils/adutils/__init__.py - ignoring
2020-01-03 19:57:12.233161 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-01-03 19:57:12.392968 INFO hello_world: Hello from AppDaemon
2020-01-03 19:57:12.395421 INFO hello_world: You are now ready to run Apps!
2020-01-03 19:57:12.396768 INFO AppDaemon: App initialization complete
```

**Comment by benleb** [comment]
@ludeeus how should one handle external libs/imports where different installed apps could have requirements for different versions of the same lib?

@CodeFinder2 can you please test the following in your setup (just replace the single import line with this) and show me the log? Thanks!
```python
try:
    from .adutils import adutils
    print("loaded via: from .adutils import adutils")
except ImportError:
    try:
        from adutils import adutils
        print("loaded via: from adutils import adutils")
    except ImportError:
        try:
            from apps.ench.adutils import adutils
            print("loaded via: from apps.ench.adutils import adutils")
        except ImportError:
            print("adutils not loaded")
            pass
```

**Comment by CodeFinder2** [comment]
Tested, log: 🙈
```text
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: AppDaemon
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.1.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (armv7 / odroid-xu)
 Home Assistant version: 0.103.5
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[20:24:47] INFO: Updating Hass.io API token in AppDaemon with the current one...
Looking in links: https://wheels.hass.io/alpine-3.10/armv7/
Collecting adutils
  Downloading https://files.pythonhosted.org/packages/10/79/ecdeab6338d9cb90b45cb7a8ba4ad8d463ff6534c319a092076559105059/adutils-0.4.5-py3-none-any.whl
Installing collected packages: adutils
Successfully installed adutils-0.4.5
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:24:54] INFO: Starting AppDaemon...
2020-01-03 20:24:56.426612 INFO AppDaemon Version 3.0.5 starting
2020-01-03 20:24:56.427172 INFO Configuration read from: /config/appdaemon/appdaemon.yaml
2020-01-03 20:24:56.430034 INFO AppDaemon: Starting Apps
2020-01-03 20:24:56.437200 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-01-03 20:24:56.662411 INFO AppDaemon: HASS: HASS Plugin Initializing
2020-01-03 20:24:56.663491 INFO AppDaemon: HASS: HASS Plugin initialization complete
2020-01-03 20:24:56.664054 INFO Starting Dashboards
2020-01-03 20:24:56.679761 INFO API is disabled
2020-01-03 20:24:56.692998 INFO AppDaemon: HASS: Connected to Home Assistant 0.103.5
2020-01-03 20:24:56.860491 INFO AppDaemon: Got initial state from namespace default
2020-01-03 20:24:58.878553 INFO AppDaemon: Reading config
2020-01-03 20:24:58.899860 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-03 20:24:58.900339 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-03 20:24:58.900728 INFO AppDaemon: App 'hello_world' added
2020-01-03 20:24:58.901077 INFO AppDaemon: App 'ench' added
2020-01-03 20:24:58.901539 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-01-03 20:24:58.902027 INFO AppDaemon: Adding /config/appdaemon/apps/ench to module import path
2020-01-03 20:24:58.902553 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils to module import path
2020-01-03 20:24:58.903085 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/.github to module import path
2020-01-03 20:24:58.903421 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/.github/workflows to module import path
2020-01-03 20:24:58.903782 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/adutils to module import path
2020-01-03 20:24:58.905221 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2020-01-03 20:24:58.929430 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/ench/ench.py
adutils not loaded
2020-01-03 20:24:58.936823 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/ench/adutils/setup.py - ignoring
2020-01-03 20:24:58.937241 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/ench/adutils/adutils/__init__.py - ignoring
2020-01-03 20:24:58.937660 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-01-03 20:24:59.262522 INFO hello_world: Hello from AppDaemon
2020-01-03 20:24:59.265318 INFO hello_world: You are now ready to run Apps!
2020-01-03 20:24:59.265602 INFO AppDaemon: Initializing app ench using class EnCh from module ench
2020-01-03 20:24:59.266568 WARNING AppDaemon: ------------------------------------------------------------
2020-01-03 20:24:59.266808 WARNING AppDaemon: Unexpected error running initialize() for ench
2020-01-03 20:24:59.267008 WARNING AppDaemon: ------------------------------------------------------------
2020-01-03 20:24:59.268124 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/appdaemon/apps/ench/ench.py", line 126, in initialize
    self.adu = adutils.ADutils(
NameError: name 'adutils' is not defined

2020-01-03 20:24:59.268362 WARNING AppDaemon: ------------------------------------------------------------
2020-01-03 20:24:59.269468 INFO AppDaemon: App initialization complete
```

**Comment by ludeeus** [comment]
> @ludeeus Wouldn't it be much better to print a more appropriate error message in HACS (something like "repo structure malformed, see bla-blub. Unable to find <list-of-missing-files>) than just a 404?

Yes, and it does, but there is a bug preventing it from showing.

> @ludeeus how should one handle external libs/imports where different installed apps could have requirements for different versions of the same lib?

I have no clue 🤷‍♂ 
If you use pip to manage you can set a range of acceptable versions,  like:
```
adutils>=0.2,<0.3
adutils>=0.2
```

**Comment by benleb** [comment]
Ok, thanks ludeeus

@CodeFinder2 Hmm to be honest, at the moment i have no clue why this does not work for you. adutils will be installed by pip in your logs and the adutils files included in the release seem all there and in correct place also. I need some time to check if I should fix this (see below) and if, how the proper way is. So to have a working app, I would recommend you to switch back to v0.4.3. Sorry. Seems the easiest would be to not use external libs at all...

Besides that, you are using Appdaemon 3.X, this is not really supported by my apps (currently implementing the new async way AD will support from 4.x on), but that should not be the problem here - at least from current perspective. But it is the problem of the "UnboundLocalError: local variable 'attrs' referenced before assignment)." error you got earlier.

**Comment by CodeFinder2** [comment]
Surprisingly, v0.4.8 seem to 'work' now (I can start it), most probably due to commit 8a05608. But I still get the `UnboundLocalError`.

So, finally, as you said, Hassio users seem to be out of luck here and cannot use this app since it is targeting features that only AD v4.x can provide. The latest AD version shipped with the Hassio addon is v3.0.5. 🤷‍♀️
(Using EnCh v0.4.3 isn't an option as well because it still has the `import hassapi as hass - ModuleNotFoundError: No module named 'hassapi'` error that I fixed in #4 .)

Off-topic but is there any specific reason why you decided to use AD 4.x and especially the `async` feature? Is there a specific advantage for this app?

**Comment by benleb** [comment]
I will check tomorrow what’s to do to make it compatible with AD 3 :)

**Comment by benleb** [comment]
@CodeFinder2 you can check the https://github.com/benleb/ad-ench/releases/tag/v0.4.10 :)

If there are issues, I suggest you open a new one as this problems seems some kind of resolved now :)

**Comment by CodeFinder2** [comment]
Done 🙂
